In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

hd = pd.read_csv("E:\Datasets\data\heart-disease.csv")

X = hd.drop("target", axis = 1)
y = hd["target"]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2)

clf = RandomForestClassifier()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

<>:6: SyntaxWarning: invalid escape sequence '\D'
<>:6: SyntaxWarning: invalid escape sequence '\D'
C:\Users\User\AppData\Local\Temp\ipykernel_9432\3355697920.py:6: SyntaxWarning: invalid escape sequence '\D'
  hd = pd.read_csv("E:\Datasets\data\heart-disease.csv")


0.8524590163934426

## Model Prediction

* Using predict()
* Using predict_proba()

In [3]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [4]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [5]:
#1. Compare the Truth and Predict the Model
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [6]:
#2 using clf.score
clf.score(X_test,y_test)

0.8524590163934426

In [8]:
#3 using accuracy score fn
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_preds)

0.8524590163934426

In [10]:
clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [11]:
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

In [12]:
hd["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

### `Predict()` can also be used for Regression models

In [15]:
#Fetch california data from sklearn
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

#converting dictinonary into a dataframe
housing_df = pd.DataFrame(housing["data"], columns=housing["feature_names"])
housing_df["target"] = housing["target"]
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [18]:
#applying a regressor model
from sklearn.ensemble import RandomForestRegressor

#setup random seed
np.random.seed(42)

#making the data ready
X = housing_df.drop("target",axis = 1)
y = housing_df["target"]

#split the data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

#Instantiate the model
model = RandomForestRegressor()

#fit the model and check accuracy
model.fit(X_train,y_train)

model.score(X_test,y_test)

0.8065734772187598

In [21]:
y_preds = model.predict(X_test)
y_preds[:10]

array([0.49384  , 0.75494  , 4.9285964, 2.54316  , 2.33176  , 1.6525301,
       2.34323  , 1.66182  , 2.47489  , 4.8344779])

In [24]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])