In [3]:
import numpy as np
import pandas as pd

In [4]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[9, 6, 9, 1, 8],
       [0, 9, 3, 2, 5],
       [5, 1, 6, 3, 5]])

In [5]:
np.sort(random_array)

array([[1, 6, 8, 9, 9],
       [0, 2, 3, 5, 9],
       [1, 3, 5, 5, 6]])

In [6]:
np.argsort(random_array)

array([[3, 1, 4, 0, 2],
       [0, 3, 2, 4, 1],
       [1, 3, 0, 4, 2]], dtype=int64)

In [8]:
random_array

array([[9, 6, 9, 1, 8],
       [0, 9, 3, 2, 5],
       [5, 1, 6, 3, 5]])

In [7]:
np.argmax(random_array,axis=0) #along vertical axis

array([0, 1, 0, 2, 0], dtype=int64)

In [9]:
np.argmax(random_array,axis=1 # along  horizontal axis

array([0, 1, 2], dtype=int64)

## converting images into numpy arrays

<img src="numpy_images/panda.png">